# Pys, Modules, and Data Science Intro

Welcome to this comprehensive guide! We will cover several essential Python topics with detailed explanations and examples:

1.  **Escape Sequences**: How to format strings with special characters.
2.  **File I/O**: Reading from and writing to files.
3.  **Modules and Packages**: Organizing code and using built-in/custom libraries.
4.  **NumPy**: A deep dive into Numerical Python, including Data Cleaning.
5.  **Pandas**: A deep dive into Data Analysis with Pandas, including Data Cleaning.

## 1. Escape Sequences

Escape sequences allow you to include special characters in strings that would otherwise be impossible or difficult to type. They always start with a backslash (`\`).

### Common Escape Sequences Table

| Escape Sequence | Description | Example |
| :--- | :--- | :--- |
| `\n` | Newline (Line Feed) | `print("Hello\nWorld")` |
| `\t` | Horizontal Tab | `print("Name:\tJohn")` |
| `\\` | Backslash | `print("C:\\Users")` |
| `\' `| Single Quote | `print('It\'s me')` |
| `\"` | Double Quote | `print("He said \"Hi\"")` |
| `\b` | Backspace | `print("Hello\bWorld")` (Removes 'o') |

In [113]:
print("Hello World")

Hello World

In [114]:
print("Hello\nWorld")

Hello
World

In [115]:
print("Blessing\"s Bag")

Blessing"s Bag

In [116]:
print("C:\\Users\\Samson\\Documents\\NGiT\\trainings\\AIML\\other-files\\conditionals.py")

C:\Users\Samson\Documents\NGiT\trainings\AIML\other-files\conditionals.py

In [117]:
print("Hello\tWorld")

Hello	World

In [118]:
print("Hello\bWorld")

HellWorld

In [119]:
# --- Examples of Escape Sequences ---

# 1. Newline: Moves the cursor to the next line
print("Line 1\nLine 2\nLine 3")
print("-" * 20)

# 2. Tab: Adds a tab space (usually 4 spaces)
print("Column 1\tColumn 2\tColumn 3")
print("Data A\tData B\tData C")
print("-" * 20)

# 3. Quotes inside strings
# Using backslash to print double quotes inside a double-quoted string
print("The teacher said, \"Please submit your assignments by Friday.\"")
# Using backslash to print single quote inside a single-quoted string
print('It\'s a beautiful day to learn Python!')
print("-" * 20)

# 4. Backslash: Printing the backslash character itself
# This is very common in Windows file paths
print("C:\\Users\\Admin\\Documents\\Python_Projects")

Line 1
Line 2
Line 3
--------------------
Column 1	Column 2	Column 3
Data A	Data B	Data C
--------------------
The teacher said, "Please submit your assignments by Friday."
It's a beautiful day to learn Python!
--------------------
C:\Users\Admin\Documents\Python_Projects

In [120]:
print("n" * 20)

nnnnnnnnnnnnnnnnnnnn

### Task 1: Escape Sequences Practice
Write a single print statement that outputs the following text exactly as shown (pay attention to tabs and newlines):

```text
Shopping List:
	* "Milk"
	* "Eggs"
	* "Bread"
Note: Don't forget the \receipt\!
```

In [121]:
# Your code here
print('Shopping List:\n "Milk"\n "Eggs"\n"Bread"\n Note: \t "Don\'t forget the\ receipt\!"')

Shopping List:
 "Milk"
 "Eggs"
"Bread"
 Note: 	 "Don't forget the\ receipt\!"

<>:2: SyntaxWarning: "\ " is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\ "? A raw string is also an option.
<>:2: SyntaxWarning: "\ " is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\ "? A raw string is also an option.
C:\Users\USER\AppData\Local\Temp\ipykernel_22348\4130655288.py:2: SyntaxWarning: "\ " is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\ "? A raw string is also an option.
  print('Shopping List:\n "Milk"\n "Eggs"\n"Bread"\n Note: \t "Don\'t forget the\ receipt\!"')

## 2. Reading and Writing Files (File I/O)

File handling is a crucial part of any programming language. Python provides built-in functions to create, read, update, and delete files.

### The `open()` Function
The key function for working with files in Python is `open()`. It takes two main parameters: `filename` and `mode`.

### File Modes

| Mode | Description |
| :--- | :--- |
| `'r'` | **Read** - Default value. Opens a file for reading, error if the file does not exist. |
| `'a'` | **Append** - Opens a file for appending, creates the file if it does not exist. |
| `'w'` | **Write** - Opens a file for writing, creates the file if it does not exist. Overwrites existing content! |
| `'x'` | **Create** - Creates the specified file, returns an error if the file exists. |

### The `with` Statement
It is best practice to use the `with` statement when working with files. It automatically closes the file for you when you are done, even if an error occurs. This prevents memory leaks and file corruption.

In [122]:
# --- Writing to a file ---
filename = "sample_data.py"

# 'w' mode overwrites any existing content
with open(filename, "w") as file:
    file.write("'My name is Python.\n'")
    file.write("'Python makes file handling very simple.\n'")
    file.write("'We are learning about the 'w' mode.\n'")

print(f"Successfully wrote to '{filename}'.")

Successfully wrote to 'sample_data.py'.

In [123]:
# --- Appending to a file ---
# 'a' mode adds content to the end of the file without deleting existing content
with open(filename, "a") as file:
    file.write("This line is appended using 'a' mode.\n")
    file.write("Notice how the previous content is still there!\n")

print(f"Successfully appended to '{filename}'.")

Successfully appended to 'sample_data.py'.

In [124]:
my_file = "wunmi.py"

with open(my_file, "a") as file:
    file.write("'My name is Wunmi and I am a python developer'\n")
    file.write("'I am currently learning file handling'\n")

In [1]:
file_name = "wunmi.py"



with open(file_name, "r") as file:
    content = file.read()
    print(type(content))

<class 'str'>

In [ ]:
file_name = "wunmi.py"

with open(file_name, "r") as file:
    content = file.readlines()
    print(type(content))

<class 'list'>

In [ ]:
# --- Reading from a file ---

# Method 1: read() - Reads the entire file content as a single string
print("--- Method 1: read() ---")
with open(filename, "r") as file:
    content = file.read()
    print(content)

# Method 2: readlines() - Reads all lines into a list
print("\n--- Method 2: readlines() ---")
with open(filename, "r") as file:
    lines = file.readlines()
    print(f"Number of lines: {len(lines)}")
    for i, line in enumerate(lines, 1):
        print(f"Line {i}: {line.strip()}") # strip() removes the newline character at the end

### Task 2: File I/O Practice
1. Create a file named `my_diary.txt`.
2. Write 3 lines about what you learned today.
3. Open the file again and append one more line about your goal for tomorrow.
4. Read the file and print each line with a prefix "Diary Entry: ".

In [ ]:
# Your code here
file_name = "my_diary.txt"
with open(file_name ,"w") as file :
 file.write ("'How to format strings with special characters'.\n")
 file.write ("'Reading to files'.\n")
 file.write ("'Writing to files'.\n")

In [ ]:
file_name = "my _diary.txt"
with open (file_name , "a") as file :
 file.write (" 'I will be doing my assignment tomorrow'.\n")
 file.write ("I will be doing my assignment tomorrow.\n")

In [ ]:
file_name = "my_dairy.txt"
with open(file_name ,"r") as file:
 for line in file:
  print ("diary entry," ,line. strip())

FileNotFoundError: [Errno 2] No such file or directory: 'my_dairy.txt'

## 3. Modules and Packages

A **module** is simply a file containing Python code. A **package** is a directory of modules containing a special `__init__.py` file.

### Why use modules?
- **Reusability**: Write code once, use it everywhere.
- **Organization**: Keep your code clean and manageable.
- **Namespace**: Avoid variable name conflicts.

### Importing Modules
You can import modules in several ways:
1. `import module_name` (Access via `module_name.function()`)
2. `import module_name as alias` (Access via `alias.function()`)
3. `from module_name import function_name` (Access directly via `function_name()`)
4. `from module_name import *` (Imports everything - generally discouraged)

In [ ]:
import math
import random

my_list = [1,2,3,4,5,6,7,8]

random.choice(my_list)
math.sqrt(25)

2

In [ ]:
# --- Using Built-in Modules ---

import math
import random
import datetime as dt

# Math module
print(f"Square root of 25: {math.sqrt(25)}")
print(f"Factorial of 5: {math.factorial(5)}")

# Random module
print(f"Random number (1-100): {random.randint(1, 100)}")
choices = ['Apple', 'Banana', 'Cherry']
print(f"Random choice: {random.choice(choices)}")

# Datetime module
now = dt.datetime.now()
print(f"Current date and time: {now}")
print(f"Current year: {now.month}")

Square root of 25: 5.0
Factorial of 5: 120
Random number (1-100): 95
Random choice: Apple
Current date and time: 2026-02-28 18:30:48.469049
Current year: 2

In [ ]:
import math as mth
import datetime as dt

today_date = dt.datetime.now()
print(today_date)

mth.sqrt(25)

2026-02-28 18:33:23.003487

5.0

### Using a Custom Module
We have a file named `my_module.py` in the current directory. Let's use it.

In [ ]:
import my_module

# Accessing a variable
print(f"Greeting from module: {my_module.greeting}")

# Accessing a function
result = my_module.add_numbers(10, 20)
print(f"Result of addition: {result}")

## 4. NumPy (Numerical Python)

NumPy is the fundamental package for scientific computing in Python. It provides support for arrays (matrices), which are much faster and more efficient than Python lists.

### Why NumPy?
- **Speed**: NumPy arrays are stored in contiguous memory locations.
- **Functionality**: Optimized built-in mathematical functions.
- **Convenience**: Easy to perform operations on entire arrays at once (broadcasting).

### Most Used NumPy Methods

| Method | Description | Example |
| :--- | :--- | :--- |
| `np.array(list)` | Creates a NumPy array from a python list | `arr = np.array([1, 2, 3])` |
| `np.zeros(shape)` | Creates an array filled with zeros | `np.zeros((2, 3))` |
| `np.ones(shape)` | Creates an array filled with ones | `np.ones((2, 3))` |
| `np.arange(start, stop, step)` | Creates an array with a range of values | `np.arange(0, 10, 2)` |
| `np.linspace(start, stop, num)` | Creates an array with `num` evenly spaced values | `np.linspace(0, 1, 5)` |
| `arr.reshape(new_shape)` | Changes the shape of an array | `arr.reshape(2, 3)` |
| `arr.shape` | Attribute returning the dimensions of the array | `(2, 3)` |
| `np.sum(arr)` | Calculates sum of all elements | `np.sum(arr)` |
| `np.mean(arr)` | Calculates average of all elements | `np.mean(arr)` |
| `np.max(arr)` / `np.min(arr)` | Finds maximum / minimum value | `np.max(arr)` |
| `np.random.rand(d0, d1)` | Generates random values between 0 and 1 | `np.random.rand(3, 2)` |

In [ ]:
import numpy as np

# --- 1. Array Creation ---
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr_1d}")

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D Array:\n{arr_2d}")
print(f"Shape of 2D Array: {arr_2d.shape}")

# --- 2. Built-in Creation Functions ---
zeros = np.zeros((3, 3))
print(f"\nZeros Array:\n{zeros}")

range_arr = np.arange(0, 20, 2) # Start at 0, stop before 20, step 2
print(f"\nRange Array: {range_arr}")

# --- 3. Array Operations ---
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition (Broadcasting)
print(f"\na + b: {a + b}")
print(f"a * 2: {a * 2}")

# Statistics
print(f"\nSum: {np.sum(a)}")
print(f"Mean: {np.mean(a)}")
print(f"Max: {np.max(a)}")

### NumPy Data Cleaning

Data cleaning is essential. In NumPy, we often deal with missing values represented as `NaN` (Not a Number).

Common tasks:
- Identifying `NaN` values: `np.isnan(arr)`
- Removing `NaN` values: Using boolean indexing
- Replacing `NaN` values: `np.nan_to_num(arr)` or custom logic

In [ ]:
# --- Handling Missing Values in NumPy ---

# Create an array with NaN (Not a Number)
data_arr = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan])
print(f"Original Array with NaNs: {data_arr}")

# Check for NaNs
has_nans = np.isnan(data_arr)
print(f"Is NaN mask: {has_nans}")

# Remove NaNs
clean_arr = data_arr[~has_nans] # ~ means 'not'
print(f"Array without NaNs: {clean_arr}")

# Replace NaNs with a value (e.g., 0)
replaced_arr = np.nan_to_num(data_arr, nan=0.0)
print(f"Array with NaNs replaced by 0: {replaced_arr}")

# Replace NaNs with the mean of valid elements
mean_val = np.nanmean(data_arr) # nanmean calculates mean ignoring NaNs
data_arr[np.isnan(data_arr)] = mean_val
print(f"Array with NaNs replaced by Mean ({mean_val}): {data_arr}")

### NumPy Practice Tasks (Data Cleaning Included)

**Task 1:** Create a NumPy array of numbers from 1 to 20. Reshape it into a 4x5 matrix (2D array) and print it.

**Task 2:** Create an array: `[10, 20, np.nan, 40, np.nan, 60]`. Find the sum of this array ignoring the NaNs (Hint: look for a specific function).

**Task 3:** Create a 1D array of 10 random numbers. Replace all values greater than 0.5 with 1.0 and all others with 0.0 (Binarization).

**Task 4:** Create a 3x3 array with `NaN` on the main diagonal. Replace these `NaN`s with the number -1.

In [ ]:
# Task 1: Reshaping
import math as mth
import pandas as pd
import numpy as np




        
# Your code here

# Task 2: Sum ignoring NaNs
# Your code here

# Task 3: Binarization
# Your code here

# Task 4: Diagonal Replacement
# Your code here

In [ ]:
my_list  = np.array( [ 1 ,2, 3, 4, 5,
                     6, 7, 8, 9 ,10,
                    11, 12, 13, 14,15,
                    16 , 17, 18, 19,20 ] )

print (my_list)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

In [ ]:
my_list = np.array ([10, 20, np.nan, 40, np. nan,60])
np.sum(my_list)

np.float64(nan)

In [7]:
import numpy as np
import random as rd

In [ ]:
for (i) in range (10) :
 print (random .random ())

0.6453837841649446
0.24012002866539917
0.32887996393805274
0.390079837773443
0.0345706275651293
0.8315544684980039
0.8395967331868726
0.5490624451540359
0.5902528649724246
0.42591713046119006

In [ ]:
my_list = np.array ([0.42, 0.59, 0.54, 0.83, 0.81, 0.03, 0.39, 0.32, 0.24, 0.64] )
print(my_list)

[0.42 0.59 0.54 0.83 0.81 0.03 0.39 0.32 0.24 0.64]

In [ ]:
my_list = np.array([0.42,0.59,0.83,0.81,0.03,0.39,0.32,0.24,0.64]) 
my_list[my_list > 0.5 ]= 1.0
my_list[my_list < 0.5] = 0.0
print (my_list)

[0. 1. 1. 1. 0. 0. 0. 0. 1.]

## 5. Pandas (Python Data Analysis Library)

Pandas is built on top of NumPy and provides high-performance, easy-to-use data structures and data analysis tools. The two primary data structures are **Series** (1D) and **DataFrame** (2D).

### Most Used Pandas Methods

| Method | Description | Example |
| :--- | :--- | :--- |
| `pd.DataFrame(data)` | Creates a DataFrame from a dictionary or list | `df = pd.DataFrame(data)` |
| `pd.read_csv(filename)` | Reads data from a CSV file | `df = pd.read_csv('data.csv')` |
| `df.head(n)` | Returns the first n rows | `df.head(5)` |
| `df.tail(n)` | Returns the last n rows | `df.tail(3)` |
| `df.info()` | Prints summary of the DataFrame (types, non-nulls) | `df.info()` |
| `df.describe()` | Generates descriptive statistics (mean, std, min, max) | `df.describe()` |
| `df.shape` | Returns dimensions (rows, columns) | `df.shape` |
| `df.columns` | Returns list of column names | `df.columns` |
| `df['col']` | Selects a single column | `df['Age']` |
| `df.loc[row, col]` | Access group of rows/cols by label | `df.loc[0, 'Name']` |
| `df.iloc[row, col]` | Access group of rows/cols by integer position | `df.iloc[0, 0]` |
| `df.drop(columns)` | Removes specified columns | `df.drop(columns=['Age'])` |
| `df.isnull().sum()` | Checks for missing values | `df.isnull().sum()` |
| `df.dropna()` | Drops rows with missing values | `df.dropna()` |
| `df.fillna(value)` | Fills missing values | `df.fillna(0)` |
| `df.duplicated()` | Checks for duplicates | `df.duplicated()` |
| `df.drop_duplicates()` | Removes duplicates | `df.drop_duplicates()` |

In [ ]:
my_list = np.array([ np.nan, 2, 3,
                    4, np.nan, 6,
                    7, 8,  np.nan] )

print (my_list)

[nan  2.  3.  4. nan  6.  7.  8. nan]

In [ ]:
my_list = np.array([ np.nan, 2, 3,
                    4, np.nan, 6,
                    7, 8,  np.nan] )
new_list =  np.nan_to_num([my_list]  , nan = -1)
print (new_list)

[[-1.  2.  3.  4. -1.  6.  7.  8. -1.]]

In [ ]:
import pandas as pd

# --- 1. Creating a DataFrame ---
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [50000, 60000, 55000, 70000, 65000]
}

df = pd.DataFrame(data)
print("--- Original DataFrame ---")
print(df)

# --- 2. Inspecting Data ---
print("\n--- First 2 rows (head) ---")
print(df.head(2))

print("\n--- DataFrame Info ---")
df.info()

print("\n--- Descriptive Statistics ---")
print(df.describe())

# --- 3. Selecting Data ---
print("\n--- Selecting 'Name' and 'Salary' ---")
print(df[['Name', 'Salary']])

# --- 4. Filtering Data ---
print("\n--- Employees older than 25 ---")
filtered_df = df[df['Age'] > 25]
print(filtered_df)

### Pandas Data Cleaning

Data cleaning is a critical step in data analysis. Real-world data is often messy, containing missing values, duplicates, or incorrect data types.

Common tasks:
- **Handling Missing Data**: `dropna()`, `fillna()`
- **Removing Duplicates**: `drop_duplicates()`
- **Data Type Conversion**: `astype()`
- **Renaming Columns**: `rename()`

In [ ]:
# --- Pandas Data Cleaning Examples ---

# Create a messy DataFrame
messy_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', None],
    'Age': [25, np.nan, 30, 25, 22],
    'Score': ['85', '90', 'NaN', '85', '70'] # Score is string type!
}
df_messy = pd.DataFrame(messy_data)

print("--- Messy DataFrame ---")
print(df_messy)

# 1. Check for missing values
print("\n--- Missing Values Count ---")
print(df_messy.isnull().sum())

# 2. Remove duplicates
df_clean = df_messy.drop_duplicates()
print("\n--- After Removing Duplicates ---")
print(df_clean)

# 3. Handling Missing Values
# Fill Name with 'Unknown'
df_clean['Name'] = df_clean['Name'].fillna('Unknown')
# Fill Age with mean age
mean_age = df_clean['Age'].mean()
df_clean['Age'] = df_clean['Age'].fillna(mean_age)

print("\n--- After Filling Missing Values ---")
print(df_clean)

# 4. Data Type Conversion
# 'Score' is object (string) because of 'NaN' string. Let's fix it.
# First, coerce errors to NaN (turn string 'NaN' to actual NaN)
df_clean['Score'] = pd.to_numeric(df_clean['Score'], errors='coerce')

# Now fill the new NaN in score with 0 or mean
df_clean['Score'] = df_clean['Score'].fillna(0)

print("\n--- Final Cleaned DataFrame ---")
print(df_clean)
print(df_clean.info())

### Pandas Practice Tasks (Data Cleaning Included)

**Task 1:** Create a DataFrame with columns `Product`, `Price`, and `Stock`. Include some `None` values and duplicate rows.

**Task 2:** Clean the DataFrame from Task 1: Remove duplicates and fill missing `Stock` values with 0.

**Task 3:** Add a new column called `Total_Value` (Price * Stock).

**Task 4:** Calculate the average price of the products. If there are any missing `Price` values, fill them with the median price before calculating.

In [25]:
import pandas as pd
Data =   {
"Product" : ["rice", "beans", "garri", "semo" ,"pepper"],
"Price"   :    [2000 ,  1800  , 1500  ,  1500 ,  1300],
"Stock"  :  [ 1200 , 'nan '  , 1400,   2500,  1000]
   

   
}

print (Data)

{'Product': ['rice', 'beans', 'garri', 'semo', 'pepper'], 'Price': [2000, 1800, 1500, 1500, 1300], 'Stock': [1200, 'nan ', 1400, 2500, 1000]}

In [26]:
import pandas as pd 

Data_df = pd.DataFrame(Data) 
print (Data_df)

  Product  Price Stock
0    rice   2000  1200
1   beans   1800  nan
2   garri   1500  1400
3    semo   1500  2500
4  pepper   1300  1000

In [17]:
Data_df.head()

  Product  Price    Stock
0    rice   2000     1200
1   beans   1800  np.nan
2   garri   1500     1400
3    semo   1500     2500
4  pepper   1300     1000

In [29]:
A = Data_df. drop_duplicates(subset='Price')
print(A)

  Product  Price Stock
0    rice   2000  1200
1   beans   1800  nan
2   garri   1500  1400
4  pepper   1300  1000

In [30]:

A.head()

  Product  Price Stock
0    rice   2000  1200
1   beans   1800  nan
2   garri   1500  1400
4  pepper   1300  1000

In [31]:
mean =Data_df["Price"].mean()
print (mean)

1620.0

In [32]:
Data_df = Data_df.fillna(0)

In [34]:
Data_df = Data_df.fillna(0)